output "sql_server_fqdn" {
  value       = azurerm_mssql_server.example.fully_qualified_domain_name
  description = "The fully qualified domain name (FQDN) of the SQL Server (e.g., xxxx.database.windows.net)."
}

output "sql_database_name" {
  value       = azurerm_mssql_database.example.name
  description = "The name of the SQL Database."
}

output "sql_server_id" {
  value       = azurerm_mssql_server.example.id
  description = "The Resource ID of the SQL Server."
}

output "sql_server_name" {
  value = azurerm_mssql_server.example.name
}

output "database_id" {
  value = azurerm_mssql_database.example.id
}

output "aws_frankfurt_ips" {
  value = data.aws_ip_ranges.frankfurt_ec2.cidr_blocks
}

# The SQL admin password, generated by this layer and also written to Key Vault.
#
# mssql_schemas used to re-read it at parse time with
# `run_cmd("az","keyvault","secret","show",...)`. That could never work: the
# secret is created by THIS layer, so the read happens before the write. (It was
# also wrapped in jsondecode() while asking az for `--output tsv`, which returns a
# bare string.) The password already lives in this module's state either way, so
# passing it through a dependency output is both correct and no less private.
output "sql_admin_password" {
  description = "Admin password for the SQL server; consumed by the mssql_schemas layer."
  value       = random_password.sql_admin.result
  sensitive   = true
}
