variable "delta_shares_map_json" {
  type        = string
  description = "A JSON-encoded map of catalogs and their shareable objects (Schemas/Volumes), grouped by catalog name. Generated by the Python governance logic."
}

variable "aws_global_metastore_id" {
  type        = string
  description = "The unique Global Sharing Identifier of the AWS Databricks Metastore (format: aws:region:uuid)."
}

variable "aws_db_recipient" {
  type        = string
  description = "The name of the Recipient object to be created in the GCP Unity Catalog to represent the AWS side."
  default     = "aws_metastore_recipient"
}