#!/usr/bin/env python3
"""Deterministic monthly cost + carbon FLOOR for the platform.

CI's Infracost step prices ``infra/aws/modules`` only — it has no Databricks
provider and limited Azure/GCP coverage (see CLAUDE.md gotcha #5). That leaves
two blind spots in any cost conversation: **Databricks compute** and **the other
two clouds**. This fills them, deterministically, from
``environments/<env>/cost_assumptions.json``.

It is an *order-of-magnitude floor*, not a bill: list prices, one region,
steady-state. The value is making the full multi-cloud + Databricks shape visible
in one number instead of an AWS-only fragment that reads as "the whole cost".

It also estimates **operational carbon** for the always-on serverless warehouse
(kWh × grid intensity × PUE) — the one piece of always-on compute in public mode —
so a sustainability figure travels next to the dollar figure.

Usage::

    python scripts/cost_estimate.py            # write docs/governance/COST.md
    python scripts/cost_estimate.py --check     # fail if COST.md is stale
    python scripts/cost_estimate.py --stdout    # print Markdown, write nothing
    python scripts/cost_estimate.py --json       # machine-readable estimate
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DEFAULT_REPORT = Path("docs/governance/COST.md")


def _assumptions_path(repo_root: Path, env: str) -> Path:
    return repo_root / "environments" / env / "cost_assumptions.json"


def compute(assumptions: dict) -> dict:
    """Turn the assumptions into a structured estimate (pure arithmetic)."""
    dbx = assumptions["databricks"]
    size = dbx["warehouse_size"]
    dbu_hr = dbx["dbu_per_hour"][size]
    hours_month = dbx["hours_per_day"] * dbx["days_per_month"]
    dbx_dbus = dbu_hr * hours_month
    dbx_cost = round(dbx_dbus * dbx["usd_per_dbu"], 2)

    infra = assumptions["infra_monthly_usd"]
    per_cloud: dict[str, float] = {}
    for cloud, items in infra.items():
        if cloud.startswith("_"):
            continue
        per_cloud[cloud] = round(float(sum(v for k, v in items.items() if not k.startswith("_"))), 2)
    infra_total = round(sum(per_cloud.values()), 2)

    # Snowflake — the second enforcement backend's compute (optional block). Credit-based:
    # the per-domain resource-monitor quota × list price per credit. Absent → 0 (the UC-only
    # cost is unchanged), so this stays backward-compatible with pre-Snowflake assumptions.
    sf = assumptions.get("snowflake")
    if sf:
        sf_credits = sf["credits_per_month"]
        sf_cost = round(sf_credits * sf["usd_per_credit"], 2)
    else:
        sf_credits = 0
        sf_cost = 0.0

    # Carbon for the always-on warehouse (the only steady-state compute in public mode).
    carbon = assumptions["carbon"]
    power_kw = dbx["power_kw"][size]
    pue = carbon.get("pue", 1.0)
    kwh_month = power_kw * hours_month * pue
    # Attribute warehouse energy to AWS (the metastore/serverless home region).
    intensity = carbon["grid_intensity_g_per_kwh"].get("AWS", 0)
    carbon_kg = round(kwh_month * intensity / 1000.0, 1)

    total = round(dbx_cost + infra_total + sf_cost, 2)
    return {
        "currency": assumptions.get("currency", "USD"),
        "databricks": {
            "warehouse_size": size,
            "dbus_per_month": dbx_dbus,
            "monthly_usd": dbx_cost,
        },
        "snowflake": {
            "credits_per_month": sf_credits,
            "monthly_usd": sf_cost,
        },
        "infra_per_cloud_usd": per_cloud,
        "infra_total_usd": infra_total,
        "total_monthly_usd": total,
        "carbon": {
            "warehouse_kwh_per_month": round(kwh_month, 1),
            "warehouse_kg_co2e_per_month": carbon_kg,
        },
    }


def render_markdown(est: dict) -> str:
    cur = est["currency"]
    out: list[str] = []
    out.append("# Platform cost & carbon — estimated monthly floor")
    out.append("")
    out.append(
        "> Generated by `scripts/cost_estimate.py` from `environments/dev/cost_assumptions.json`. "
        "Order-of-magnitude **floor**, not a bill (list prices, single region, steady-state). "
        "It complements the CI Infracost comment, which prices AWS infra only — here Databricks "
        "compute and all three clouds are in one figure."
    )
    out.append("")
    out.append(
        f"**Estimated total: ~{est['total_monthly_usd']:,.0f} {cur}/month** "
        f"· **carbon: ~{est['carbon']['warehouse_kg_co2e_per_month']:,.0f} kg CO₂e/month** (serverless warehouse)"
    )
    out.append("")
    out.append("## Databricks compute")
    out.append("")
    d = est["databricks"]
    out.append("| Item | Value |")
    out.append("| --- | --- |")
    out.append(f"| Serverless SQL warehouse size | {d['warehouse_size']} |")
    out.append(f"| DBUs / month | {d['dbus_per_month']:,.0f} |")
    out.append(f"| Cost / month | {d['monthly_usd']:,.2f} {cur} |")
    out.append("")
    sf = est.get("snowflake", {})
    if sf.get("monthly_usd", 0):
        out.append("## Snowflake compute (second enforcement backend)")
        out.append("")
        out.append("| Item | Value |")
        out.append("| --- | --- |")
        out.append(f"| Credits / month (resource-monitor quota) | {sf['credits_per_month']:,.0f} |")
        out.append(f"| Cost / month | {sf['monthly_usd']:,.2f} {cur} |")
        out.append("")
    out.append("## Per-cloud infrastructure")
    out.append("")
    out.append(f"| Cloud | Monthly {cur} |")
    out.append("| --- | --- |")
    for cloud, cost in est["infra_per_cloud_usd"].items():
        out.append(f"| {cloud} | {cost:,.2f} |")
    out.append(f"| **Infra total** | **{est['infra_total_usd']:,.2f}** |")
    out.append("")
    out.append("## Carbon (operational, serverless warehouse)")
    out.append("")
    c = est["carbon"]
    out.append("| Item | Value |")
    out.append("| --- | --- |")
    out.append(f"| Energy / month | {c['warehouse_kwh_per_month']:,.1f} kWh |")
    out.append(f"| Emissions / month | {c['warehouse_kg_co2e_per_month']:,.1f} kg CO₂e |")
    out.append("")
    return "\n".join(out) + "\n"


def generate(repo_root: str | Path, env: str = "dev") -> tuple[str, dict]:
    repo_root = Path(repo_root).resolve()
    assumptions = json.loads(_assumptions_path(repo_root, env).read_text(encoding="utf-8"))
    est = compute(assumptions)
    return render_markdown(est), est


def _default_repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Estimate the platform's monthly cost + carbon floor (offline, deterministic).")
    parser.add_argument("--root", default=str(_default_repo_root()))
    parser.add_argument("--env", default="dev", help="environment whose cost_assumptions.json to read (default: dev)")
    parser.add_argument("--check", action="store_true", help="fail if committed COST.md is stale")
    parser.add_argument("--stdout", action="store_true", help="print Markdown, write nothing")
    parser.add_argument("--json", action="store_true", help="print the machine-readable estimate")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    markdown, est = generate(root, args.env)

    if args.json:
        print(json.dumps(est, indent=2))
        return 0
    if args.stdout:
        print(markdown, end="")
        return 0

    path = root / DEFAULT_REPORT
    if args.check:
        existing = path.read_text(encoding="utf-8") if path.is_file() else ""
        if existing != markdown:
            print(f"STALE cost estimate (run `make cost-estimate`): {DEFAULT_REPORT}")
            return 1
        print("cost estimate is up to date.")
        return 0

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown, encoding="utf-8")
    print(f"wrote {DEFAULT_REPORT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
