#!/usr/bin/env python3
"""Governance telemetry — trendable metrics over the committed config.

The analyzer answers *"is the access model safe right now?"*. This answers the
adjacent question a platform owner tracks over time: *"is governance hygiene
improving or regressing, and what is about to need attention?"*

It derives a small, deterministic metrics document from the same offline model:

* **posture** — open findings by severity + accepted (documented) risks.
* **coverage** — % of schemas classified, % of catalogs owned (the hygiene the
  LOW rules nag about, expressed as a trend line instead of a list).
* **pii** — how many datasets hold PII and how many sit in federated storage.
* **exceptions timeline** — how many exceptions expire within 30/60/90 days (and
  how many are already expired). Date-dependent, so excluded from ``--check``.

``docs/governance/metrics.json`` is regenerated by ``make governance-report`` and
CI asserts the deterministic part is in sync (``--check``) — the same discipline
as the report and Genie artifacts. Commit it and a reviewer can diff the platform's
governance posture between PRs; a badge or dashboard can trend it over time.

Usage::

    python scripts/governance_metrics.py            # write docs/governance/metrics.json
    python scripts/governance_metrics.py --check     # fail if the deterministic part is stale
    python scripts/governance_metrics.py --stdout    # print JSON, write nothing
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import sys
from pathlib import Path

from governance_model import GovernanceModel, build_model
from policy_analyzer import (
    HIGH,
    INFO,
    LOW,
    MEDIUM,
    AnalysisResult,
    expiring_exceptions,
    load_exceptions,
    run_analysis,
)

DEFAULT_METRICS = Path("docs/governance/metrics.json")
_EXCEPTIONS = Path("environments/dev/policy_exceptions.json")

# Keys whose value depends on the run date — excluded from the --check compare so
# CI stays deterministic (same idea as governance_report's generated_at strip).
_VOLATILE_KEYS = ('"generated_at"', '"expired"', '"expiring_within_30d"', '"expiring_within_60d"', '"expiring_within_90d"')


def _pct(part: int, whole: int) -> float:
    return round(100.0 * part / whole, 1) if whole else 100.0


def build_metrics(
    model: GovernanceModel,
    analysis: AnalysisResult,
    exceptions_path: Path,
    *,
    today: _dt.date | None = None,
) -> dict:
    """Assemble the metrics document from the offline governance model."""
    today = today or _dt.date.today()

    schemas = [s for s in model.securables if s.object_type == "schema"]
    catalogs = [s for s in model.securables if s.object_type == "catalog"]
    classified = [s for s in schemas if s.classification is not None]
    owned = [c for c in catalogs if c.owner]
    pii_objects = [s for s in model.securables if s.classification == "pii" and s.object_type in ("schema", "volume")]
    pii_federated = [s for s in pii_objects if s.catalog_type == "FEDERATED"]

    counts = analysis.counts()
    exceptions = load_exceptions(exceptions_path)

    def _expiring(days: int) -> int:
        return len([e for e in expiring_exceptions(exceptions, within_days=days, today=today) if e.days_left >= 0])

    expired = len([e for e in expiring_exceptions(exceptions, within_days=0, today=today) if e.days_left < 0])

    return {
        "generated_at": today.isoformat(),
        "posture": {
            "open_high": counts[HIGH],
            "open_medium": counts[MEDIUM],
            "open_low": counts[LOW],
            "info": counts[INFO],
            "accepted_risks": counts["ACCEPTED"],
            "gating": len(analysis.gating),
        },
        "coverage": {
            "schemas": len(schemas),
            "schemas_classified": len(classified),
            "schemas_classified_pct": _pct(len(classified), len(schemas)),
            "catalogs": len(catalogs),
            "catalogs_owned": len(owned),
            "catalogs_owned_pct": _pct(len(owned), len(catalogs)),
        },
        "pii": {
            "datasets": len(pii_objects),
            "in_federated_storage": len(pii_federated),
        },
        "footprint": {
            "clouds": sorted({s.cloud for s in model.securables}),
            "domains": [d for _, d in model.domains()],
            "objects": len(model.securables),
            "grants": len(model.grants),
        },
        "exceptions": {
            "total": len(exceptions),
            "expired": expired,
            "expiring_within_30d": _expiring(30),
            "expiring_within_60d": _expiring(60),
            "expiring_within_90d": _expiring(90),
        },
    }


def generate(repo_root: str | Path) -> dict:
    repo_root = Path(repo_root).resolve()
    model = build_model(repo_root)
    analysis = run_analysis(repo_root)
    return build_metrics(model, analysis, repo_root / _EXCEPTIONS)


def _strip_volatile(text: str) -> str:
    return "\n".join(line for line in text.splitlines() if not any(k in line for k in _VOLATILE_KEYS))


def _default_repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate governance telemetry metrics from the committed config (offline).")
    parser.add_argument("--root", default=str(_default_repo_root()))
    parser.add_argument("--check", action="store_true", help="fail if the deterministic part of metrics.json is stale")
    parser.add_argument("--stdout", action="store_true", help="print JSON to stdout, write nothing")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    metrics = generate(root)
    payload = json.dumps(metrics, indent=2) + "\n"

    if args.stdout:
        print(payload, end="")
        return 0

    path = root / DEFAULT_METRICS

    if args.check:
        existing = path.read_text(encoding="utf-8") if path.is_file() else ""
        if _strip_volatile(existing) != _strip_volatile(payload):
            print(f"STALE metrics (run `make governance-report`): {DEFAULT_METRICS}")
            return 1
        print("governance metrics are up to date.")
        return 0

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(payload, encoding="utf-8")
    print(f"wrote {DEFAULT_METRICS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
