# --- GCP Provider Variables ---

variable "gcp_serverless_workspace_host" {
  type        = string
  description = "The host URL of the Databricks workspace on GCP."
}

variable "gcp_dbx_account_id" {
  type        = string
  description = "The Databricks Account ID for GCP."
}

variable "gcp_spn_client_id" {
  type        = string
  description = "The Client ID of the Service Principal for GCP authentication."
}

variable "gcp_spn_client_secret" {
  type        = string
  description = "The Client Secret of the Service Principal for GCP authentication."
  sensitive   = true
}

# --- AWS Provider Variables ---

variable "serverless_workspace_host" {
  type        = string
  description = "The host URL of the Databricks workspace on AWS."
}

variable "dbx_account_id" {
  type        = string
  description = "The Databricks Account ID for AWS."
}

variable "spn_client_id" {
  type        = string
  description = "The Client ID of the Service Principal for AWS authentication."
}

variable "spn_client_secret" {
  type        = string
  description = "The Client Secret of the Service Principal for AWS authentication."
  sensitive   = true
}

# --- Delta Sharing Logic Variables ---

variable "delta_shares_map_json" {
  type        = string
  description = "JSON-encoded map containing the catalogs and objects to be shared, generated by the Python governance logic."
}

variable "aws_global_metastore_id" {
  type        = string
  description = "The Global Metastore ID of the AWS Databricks environment (format: aws:region:uuid). This should come from the AWS bootstrap output."
}

variable "gcp_metastore_id" {
  type        = string
  description = "The Unique ID of the GCP Databricks Metastore (Global Metastore ID)"
}

variable "gcp_provider_name" {
  type        = string
  description = "The Delta Sharing Organization Name of the GCP Metastore, as it appears in the AWS Providers list."
}